### ISSUE TITLE
Is it possible to use this with FragmentFactory?

### ISSUE THREAD

**Issue by matpag** [Nimrodda/github-commit-browser#1]
Hi Nimrod, 
I'm trying to add `FragmentFactory` to your example but I'm blocked in a circular dependency.

Usually constructor injected `Fragment`s are like this when used with `FragmentFactory`

```
class Fragment @Inject constructor (
    private val viewModelFactory: ViewModelProvider.Factory
) : Fragment() { 
    private val viewModel: MyViewModel by viewModels { viewModelFactory }
}
```

The problem I have it's that now with the AssistedInjected ViewModelFactory my Fragment code should change to something like this:

```
class Fragment @Inject constructor (
    private val viewModelFactory: ViewModelFactory
) : Fragment() { 
    private val viewModel: MyViewModel by viewModels { viewModelFactory }
}
```

But here the circular dependency: 
`Fragment` needs `ViewModelFactory` to be created -> 
`ViewModelFactory` need a `SavedStateRegistryOwner` to be created -> 
I can't create the `Fragment` to get one. 

Do you have ideas on how this could be solved? 
BTW Thank you for you article 👍

**Comment by Nimrodda** [comment]
Sorry for over a one year delay in response 😬 
I guess you'd probably figured this out by now?
Until recently I was using FragmentFactory, but after migrating to Hilt, I switched back to member injection in Fragments. It just works better currently with Hilt. If you'd like to see how I solved it prior to the migration, check out branch `savedstate-factories`.
