### ISSUE TITLE
Navgraph viewmodels

### ISSUE THREAD

**Issue by kenshin171** [Nimrodda/github-commit-browser#2]
for viewmodels that are bound to navgraphs instead of activities or fragments, how do we create the savedstateRegistryOwner?

as below
```
@Binds
    abstract SavedStateRegistryOwner bindSavedStateRegistryOwner(CommitListFragment commitListFragment);
```

**Comment by Nimrodda** [comment]
Sorry for the long delay in my response.
It's not possible unfortunately. I updated my article to reflect that and I now recommend against using AssistedInject.
With the new Dagger Hilt, you no longer need to implement a ViewModel factory. Check out [this PR](https://github.com/Nimrodda/github-commit-browser/pull/5) for more details.

**Comment by kenshin171** [comment]
@Nimrodda thanks for your response, i actually did it like this, and it seems to work fine, with assistedInject. But i do agree that `Hilt` is a much cleaner simpler approach.
```
@Inject
lateinit var factory: DaggerViewModelFactory

private val viewModel: SomeViewModel
        by navGraphViewModels(R.id.some_navigation) {
            factory.create(findNavController().getBackStackEntry(R.id.some_navigation))
}
```
